### ISSUE TITLE
Article 4 figcaption

### ISSUE THREAD

**Issue by FMezard** [isawnyu/isaw-papers#15]
The figures in article 4 have a title and a caption: how should the css deal with that ? Should we keep it the way it was done before  or try to uniform things? 
Before: 
```css
p.figure_title {font-family:sans-serif;text-indent:0;font-size:smaller;font-weight:bold;text-align:center;margin-bottom:1em}
p.figure_caption {font-family:sans-serif;text-indent:0;font-size:smaller; margin-bottom:2em;}
``` 
The `p.figure_title` is also used in the articles 3 and 6.
